language: node_js
node_js:
  - "node"

addons:
  chrome: stable

before_script: cp src/secrets.js.template src/secrets.js

script:
  - npm run lint:code
  - npm run lint:style
  - npm run test
  - npm run build
